### ISSUE TITLE
java.lang.NullPointerException when reading a BEAM-DIMAP from a Django web app

### ISSUE THREAD

**Issue by h4k1m0u** [senbox-org/snap-engine#104]
I'm not sure if this is the right repo to ask a question about a problem I'm facing with `snappy`.
So, I have a `Django` web app inside of which I have just a call to ` ProductIO.readProduct()`, as follows:

```python
    def test(request):
        path_sar = '<path>/file.dim'
        sar_pre_product = ProductIO.readProduct(path_sar)
```

The following Java exception `java.lang.NullPointerException` is thrown specifically when the SAR image given as input is in the `BEAM-DIMAP` format; If I use a `GeoTIFF` it works well, but I can't use a `GeoTIFF` image because the metadata is needed to calibrate the SAR product.

Also the two lines of code above work from the command-line (and from Django's shell) normally even with a `BEAM-DIMAP` file.

Anyone has an idea where this error can come from and why it appears only when the product is of type `BEAM-DIMAP` and is read in the browser?

**Comment by marpet** [comment]
Actually BEAM-DIMAP should be readable at all. And you say it works from the command line. This makes me think that something is wrong with the classpath in your web app. What about the stacktrace of the exception. Could you post it?

**Comment by h4k1m0u** [comment]
Sorry for the delay, I had some issues with the machine I was working on. So now that I'm on Python36, the same issue appear, it seems that it's a `heap size` error. Please find below the stacktrace printed on the command line:

```sh
INFO: org.hsqldb.persist.Logger: dataFileCache open start
Path: C:\Users\ab01069\Dropbox\PhD\flood-monitoring\floodmonitoring\media\preprocessed-pre.tif
Java heap space
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
Internal Server Error: /extent/preprocess
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ab01069\Dropbox\PhD\flood-monitoring\floodmonitoring\maps\views.py", line 64, in preprocess
    path_sar_pre_preprocessed, 'GeoTIFF')
RuntimeError: java.lang.NullPointerException
ERROR:django.request:Internal Server Error: /extent/preprocess
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ab01069\Dropbox\PhD\flood-monitoring\floodmonitoring\maps\views.py", line 64, in preprocess
    path_sar_pre_preprocessed, 'GeoTIFF')
RuntimeError: java.lang.NullPointerException
[13/Apr/2018 22:08:45] "POST /extent/preprocess HTTP/1.1" 500 77800
```

**Comment by h4k1m0u** [comment]
The error was basically appearing because I forgot to copy the generated `jpy` wheel file to `snappy`'s folder, before configuring it with `snappy-conf <python-exe>`.

**Comment by h4k1m0u** [comment]
It seems that I'm still experiencing the same issue, though I can't remember why I though I've solved it last time (I think I started using GeoTIFF files). Below is the stacktrace:

```bash
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ab01069\Dropbox\PhD\flood-monitoring\floodmonitoring\depth\views.py", line 17, in test
    sar_pre_product = ProductIO.readProduct(p)
RuntimeError: java.lang.NullPointerException
ERROR:django.request:Internal Server Error: /depth/test
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ab01069\Dropbox\PhD\flood-monitoring\floodmonitoring\depth\views.py", line 17, in test
    sar_pre_product = ProductIO.readProduct(p)
RuntimeError: java.lang.NullPointerException
[09/May/2018 19:27:27] "GET /depth/test HTTP/1.1" 500 75226
```

**Comment by h4k1m0u** [comment]
It seems to have  been fixed in `Snap 6.0.x` (6.0.4 in my case).
I don't get that error anymore with the calibration of subsets from TerraSAR-X products, even when these are in `GeoTIFF`.

**Comment by marpet** [comment]
I think in your environment the JTS library is missing on the classpath.
http://mvnrepository.com/artifact/com.vividsolutions/jts/1.13

**Comment by h4k1m0u** [comment]
I'm not really used to Java.
To which classpath should I add this library, since my project is in Python?
Do you mean the Java classpath?

**Comment by marpet** [comment]
I thought you use a Django web app and that you need to specify it there.
If you simply use a simple Python script and it is not working, would guess that the SNAP installation is corrupted. Does an import of the DIMAP file work within SNAP Desktop?

**Comment by h4k1m0u** [comment]
Yes `ProductIO.readProduct() is failing only when called from a Django web app (it works in a normal python script).
I'm not sure if the SNAP installation is corrupted, but I have no problem opening the same BEAM-DIMAP file from inside SNAP.

**Comment by marpet** [comment]
Then it seems a problem with Django. And I can't help with it. Sorry.

**Comment by h4k1m0u** [comment]
No worries.

The ugly workaround I've found is to put that piece of code inside a python script (let's call it: `test.py`) and call it from the Django view using `subprocess.call(['python', 'test.py'])`.
