### ISSUE TITLE
Export to NetCDF Dataset raise Error: "numElems is less than one" 

### ISSUE THREAD

**Issue by radiusJS** [senbox-org/snap-engine#110]
I tried to use the gpt command line tool to write the result of a subset step to a NetCDF file. By doing this I get following error message. 

As an Input data set I used a sea surface temperature NetCDF-CF data set from the Ifremer institute. See file attached. If using other output format then NetCDF it writes the results to the target file as expected.

Also same error raise up if the tool run on windows and macOS. 

SNAP-Engine version: 6.0.4
Windows 7 64bit

**Command**
``gpt.exe subset_north_atlantic.xml -Ssource="20110101-IFR-L4_GHRSST-SSTfnd-ODYSSEA-GLOB_010-v2.0-fv1.0.nc" -f NetCDF4-CF -t "test.nc"``

```
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO

: Initializing external tool adapters
Executing processing graph
WARNING: org.esa.snap.dataio.netcdf.util.MetadataUtils: Missing configuration property 'snap.dataio.netcdf.metadataElementLimit'. Using default (100).
INFO: org.hsqldb.persist.Logger: dataFileCache open start
WARNING: org.esa.snap.dataio.netcdf.util.TimeUtils: Failed to parse time string '20101231T120000Z 00:00:00'
WARNING: org.esa.snap.dataio.netcdf.util.TimeUtils: Failed to parse time string '20110101T120000Z 00:00:00'
22%90% done.
org.esa.snap.core.gpf.OperatorException: numElems is less than one
        at org.esa.snap.core.gpf.graph.GraphProcessor$GPFImagingListener.errorOccurred(GraphProcessor.java:363)
        at com.sun.media.jai.util.SunTileScheduler.sendExceptionToListener(SunTileScheduler.java:1646)
        at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:921)
        at javax.media.jai.OpImage.getTile(OpImage.java:1129)
        at com.sun.media.jai.util.RequestJob.compute(SunTileScheduler.java:247)
        at com.sun.media.jai.util.WorkerThread.run(SunTileScheduler.java:468)
Caused by: java.lang.IllegalArgumentException: numElems is less than one
        at org.esa.snap.core.datamodel.ProductData.createInstance(ProductData.java:216)
        at org.esa.snap.dataio.netcdf.metadata.profiles.cf.CfFlagCodingPart.writeFlagCoding(CfFlagCodingPart.java:55)
        at org.esa.snap.dataio.netcdf.metadata.profiles.beam.BeamFlagCodingPart.preEncode(BeamFlagCodingPart.java:57)
        at org.esa.snap.dataio.netcdf.NetCdfWriteProfile.writeProduct(NetCdfWriteProfile.java:48)
        at org.esa.snap.dataio.netcdf.DefaultNetCdfWriter.writeProductNodesImpl(DefaultNetCdfWriter.java:62)
        at org.esa.snap.core.dataio.AbstractProductWriter.writeProductNodes(AbstractProductWriter.java:109)
        at org.esa.snap.core.gpf.common.WriteOp.doExecute(WriteOp.java:304)
        at org.esa.snap.core.gpf.internal.OperatorContext.executeOperator(OperatorContext.java:1243)
        at org.esa.snap.core.gpf.internal.OperatorImage.computeRect(OperatorImage.java:65)
        at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
        at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
        ... 3 more

Error: numElems is less than one
```
[error_numElems_itest_data.zip](https://github.com/senbox-org/snap-engine/files/2228034/error_numElems_itest_data.zip)

**Comment by marpet** [comment]
Thanks for your report. The root cause is that the netCDF file is not CF compliant. 
If you open the file in SNAP you can already see that the flags for the 'mask' band are not defined. And this leads to the error "numElems is less than one".

The problem is the 'flag_masks' attribute of the 'mask' variable. It is defined as a String but actually, it should be an array of the same data type as the variable.

That's the snippet from ncdump:
```
byte mask(time, lat, lon) ;
                mask:long_name = "land sea ice lake bit mask" ;
                mask:_FillValue = 0b ;
                mask:valid_min = 0b ;
                mask:valid_max = 12b ;
                mask:flag_masks = "0b, 1b, 2b, 3b" ;
                mask:flag_meanings = "sea land lake ice" ;
                mask:source_data = "From GMT grdlandmask" ;
```

If you don't need the mask band you can include only the bands you want in the subset step. If you need it, you can use the BandMath to create a copy of the mask band and merge it into the final product. You will lose the meanings but at least keep the values. 
It is also strange that the FillValue is 0, this is actually **sea**. 
And if I look at the data I see values of 1, 2, 6 and 9. 
Where 
1=sea
2=lake
6=land
9=ice

**Comment by marpet** [comment]
In this document the flag_masks is specified:
https://cdn.earthdata.nasa.gov/conduit/upload/504/cf-conventions_v1.4.pdf
On page 19.

**Comment by radiusJS** [comment]
Thank you very much for your fast reply and this great answer. Now it is quite obvious what the problem actually. I am sorry for blaming SNAP for this. 
I will deal with the mask variable separately in my approach in order to handle CF compliant and uncompliant data.
Beside maybe it would be nice to have a more meaningful error messages or a check if the data are CF compliant.
You've helped me so much. Thank you!
