### ISSUE TITLE
Linux failed to "readproduct"

### ISSUE THREAD

**Issue by Ixiodor** [senbox-org/snap-engine#120]
I'm trying to open a product on Linux trought Python, this solution works on Windows. This is the error log i get from running this script:

> *BEFORE READ PRODUCT*
java.lang.UnsatisfiedLinkError: no jhdf5 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at ncsa.hdf.hdf5lib.H5.loadH5Lib(H5.java:339)
        at ncsa.hdf.hdf5lib.H5.<clinit>(H5.java:266)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.esa.snap.dataio.hdf5.Hdf5ProductWriterPlugIn.loadHdf5Lib(Hdf5Prod                                                                                                                                                             uctWriterPlugIn.java:148)
        at org.esa.snap.dataio.hdf5.Hdf5ProductWriterPlugIn.<clinit>(Hdf5Product                                                                                                                                                             WriterPlugIn.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct                                                                                                                                                             orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC                                                                                                                                                             onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:3                                                                                                                                                             80)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.esa.snap.SnapCoreActivator.loadServices(SnapCoreActivator.java:60                                                                                                                                                             )
        at org.esa.snap.core.dataio.ProductIOPlugInManager.<init>(ProductIOPlugI                                                                                                                                                             nManager.java:194)
        at org.esa.snap.core.dataio.ProductIOPlugInManager$Holder.<clinit>(Produ                                                                                                                                                             ctIOPlugInManager.java:199)
        at org.esa.snap.core.dataio.ProductIOPlugInManager.getInstance(ProductIO                                                                                                                                                             PlugInManager.java:45)
        at org.esa.snap.core.dataio.ProductIO.getProductReaderForInput(ProductIO                                                                                                                                                             .java:255)
        at org.esa.snap.core.dataio.ProductIO.readProductImpl(ProductIO.java:214                                                                                                                                                             )
        at org.esa.snap.core.dataio.ProductIO.readProduct(ProductIO.java:186)
WARNING: org.esa.snap.dataio.hdf5.Hdf5ProductWriterPlugIn: class org.esa.snap.da                                                                                                                                                             taio.hdf5.Hdf5ProductWriterPlugIn: HDF-5 library not available: class java.lang.                                                                                                                                                             UnsatisfiedLinkError: ncsa.hdf.hdf5lib.H5.H5dont_atexit()I
*AFTER READ PRODUCT, my product is None*

call is "product = snap.ProductIO.readProduct([pathToProduct])"
I was forced to use JDK11 cause JDK10 is deprecated.

**Comment by marpet** [comment]
Please check this thread in the SNAP Forum:
https://forum.step.esa.int/t/snappy-hdf5-error/867

We are closing the issues in GitHub in favour of discussing them in the SNAP Forum and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.

**Comment by marpet** [comment]
By the way, SNAP is not guaranteed to work with Java 10 or 11.
It was build for Java 8.
