### ISSUE TITLE
not possibile to export products derive from Optical-Land Thematic Processing Biophysical Processor

### ISSUE THREAD

**Issue by safalabolo** [senbox-org/snap-engine#58]
There currently seems to be not possibile to export, for example geotiff format products (LAI, fAPAR) derived from the menu (Optical-Land Thematic Processing Biophysical Processor).
They operate the atmospheric correction with sen2cor tool;
then resampling the same resolution;
I derive the products for LAI products, fAPAR..ma that I can not export them.
Thanks in advance for your response and for support.

**Comment by marpet** [comment]
I often get the following error:
`java.lang.NullPointerException
	at org.esa.s2tbx.dataio.openjpeg.OpenJpegExecRetriever.findOpenJpegExecPath(OpenJpegExecRetriever.java:94)
	at org.esa.s2tbx.dataio.openjpeg.OpenJpegExecRetriever.getOpjDecompress(OpenJpegExecRetriever.java:56)
	at org.esa.s2tbx.dataio.jp2.internal.JP2TileOpImage.decompressTile(JP2TileOpImage.java:196)
	at org.esa.s2tbx.dataio.jp2.internal.JP2TileOpImage.computeRect(JP2TileOpImage.java:135)
	at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
Caused: org.esa.snap.core.gpf.OperatorException
	at org.esa.snap.core.gpf.internal.OperatorExecutor$GPFImagingListener.errorOccurred(OperatorExecutor.java:375)
	at com.sun.media.jai.util.SunTileScheduler.sendExceptionToListener(SunTileScheduler.java:1646)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:921)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
...
`

Do you get the same?
It seems to be independent from the processor used. It happens already when trying to save the resampled product.

**Comment by safalabolo** [comment]
Dear marpet,
thanks for your reply.
Currently I have the following problem.
I would like perform the following calculation step from the command line to an acquisition sentinel-2:
1)resampling (necessary for the subset)
2)subset (select only some bands)
3)Deriving biophysical products (LAI, etc)
4)Perform a linear combination of the bands to derive an albedo.

Thanks in advance for your response and for support.

**Comment by marpet** [comment]
And what is the actual problem? Where is the point you struggle?
In general I would say you simply create graph xml file and let it run with gpt.

Also I think the [Forum](http://step.esa.int) is better suited for such discussions.

**Comment by learn2014** [comment]
Hi @marpet 
I am wondering f you have the link where I could find  the documents where the Biophysical Processor equations are described in details which have been used to calculate FCV.FAPAR,LAI..etc ?
Thanks a lot for your help.
M

**Comment by marpet** [comment]
HI @learn2014 
Please ask this in the [forum](http://forum.step.esa.int/). There you will find the guys who are responsible for the Biophysical Processors.
