### ISSUE TITLE
Unable to open any NetCDF file

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-engine#62]
Just updated to 4.0.2 and get an exception whenever I try to open a NetCDF file, going to try a fresh install

```
java.lang.ClassNotFoundException: ucar.nc2.util.DebugFlagsImpl
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: ucar.nc2.util.DebugFlagsImpl starting from ModuleCL@3f5e02b9[org.esa.snap.seadas.seadas.reader] with possible defining loaders [ModuleCL@6248d856[org.esa.s1tbx.s1tbx.io]] and declared parents [ModuleCL@7da0ba77[org.esa.snap.snap.core], ModuleCL@36279ce9[org.esa.snap.snap.netcdf], ModuleCL@7b00600a[org.esa.snap.ceres.core], ModuleCL@43906558[org.esa.s3tbx.s3tbx.merisl3.reader], ModuleCL@6b9227e4[org.esa.snap.snap.ui]]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Caused: java.lang.NoClassDefFoundError: ucar/nc2/util/DebugFlagsImpl
	at gov.nasa.gsfc.seadas.dataio.L1BGociProductReaderPlugIn.getDecodeQualification(L1BGociProductReaderPlugIn.java:69)
	at org.esa.snap.rcp.actions.file.ProductOpener.lambda$getPluginsForFile$215(ProductOpener.java:262)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at org.esa.snap.rcp.actions.file.ProductOpener.getPluginsForFile(ProductOpener.java:261)
	at org.esa.snap.rcp.actions.file.ProductOpener.openProductFilesCheckOpened(ProductOpener.java:217)
	at org.esa.snap.rcp.actions.file.ProductOpener.openProduct(ProductOpener.java:103)
	at org.esa.snap.rcp.actions.file.OpenProductAction.execute(OpenProductAction.java:125)
	at org.esa.snap.rcp.actions.file.OpenProductAction.actionPerformed(OpenProductAction.java:110)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI.doClick(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by LupusUmbrae** [comment]
Fresh install and update seemed to resolve this issue.

**Comment by marpet** [comment]
Thanks for the report. Probably something went wrong during the download of the update.
