### ISSUE TITLE
java.lang.NoClassDefFoundError: ucar/nc2/util/DebugFlagsImpl

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-engine#64]
Started SNAP this morning and tried to open a NetCDF file but got this error. 

Had this before after an update which was resolved by a re-install but this time it seems to have just occurred randomly. I'll do a re-install shortly to resolve this.

```
java.lang.NoClassDefFoundError: ucar/nc2/util/DebugFlagsImpl
	at gov.nasa.gsfc.seadas.dataio.L1BGociProductReaderPlugIn.getDecodeQualification(L1BGociProductReaderPlugIn.java:69)
	at org.esa.snap.rcp.actions.file.ProductOpener.lambda$getPluginsForFile$153(ProductOpener.java:262)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at org.esa.snap.rcp.actions.file.ProductOpener.getPluginsForFile(ProductOpener.java:261)
	at org.esa.snap.rcp.actions.file.ProductOpener.openProductFilesCheckOpened(ProductOpener.java:217)
	at org.esa.snap.rcp.actions.file.ProductOpener.openProduct(ProductOpener.java:178)
	at org.esa.snap.rcp.actions.file.OpenProductAction.execute(OpenProductAction.java:125)
	at org.esa.snap.rcp.actions.file.OpenProductAction.actionPerformed(OpenProductAction.java:110)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by LupusUmbrae** [comment]
Full log file
[messages.txt](https://github.com/senbox-org/snap-engine/files/489168/messages.txt)

**Comment by marpet** [comment]
It seems that one dependency is missing in your installation which is normally located at 
<SNAP_INSTALL_DIR>\snap\modules\ext\org.esa.snap.snap-netcdf\edu-ucar\netcdf.jar
Can you check if it is there?

**Comment by LupusUmbrae** [comment]
Sadly i re-installed the application but if/when this happens again i know where to check for the jars.
