### ISSUE TITLE
gpt: spurious log messages on linux

### ISSUE THREAD

**Issue by bleutner** [senbox-org/snap-engine#80]
Hi, 

on multiple Ubuntu boxes I get this message when processing  graphs with snap gpt:

`SEVERE: org.esa.s2tbx.dataio.gdal.GDALInstaller: The GDAL library is available only on Windows operation system.`

GDAL is available on all these machines and it doesn't seem to cause any further problems, but since it is tagged "SEVERE" I thought I let you know.

SNAP version: 5.0.3

Best,
Benjamin

**Comment by marpet** [comment]
Yes, it's true. This shouldn't be logged, at least not as as severe log message.

You have installed GDAl but SNAP is not configured to use it. That's why the message is shown.

Thanks for the report.

@kraftek Can you take of this?

**Comment by kraftek** [comment]
This should have been addressed by the update 5.0.6.
Could you please confirm that, by updating to 5.0.6, the reported issue no longer manifests?

Regards

**Comment by marpet** [comment]
But 5.0.6 is not yet released, @kraftek.

**Comment by bleutner** [comment]
Yes, the message no longer shows in 5.0.6

Now I do get this warning however:

/opt/snap/bin/gpt -h
```
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALPlugInActivator: The environment variable LD_LIBRARY_PATH is not set. It must contain the current folder '.'.
java.lang.IllegalArgumentException: The environment variable LD_LIBRARY_PATH is not set. It must contain the current folder '.'.
	at org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller.processInstalledLinuxDistribution(GDALDistributionInstaller.java:109)
	at org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller.install(GDALDistributionInstaller.java:82)
	at org.esa.s2tbx.dataio.gdal.activator.GDALPlugInActivator.start(GDALPlugInActivator.java:22)
	at org.esa.snap.runtime.Engine.informActivators(Engine.java:222)
	at org.esa.snap.runtime.Engine.lambda$start$0(Engine.java:121)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Engine.start(Engine.java:121)
	at org.esa.snap.runtime.Engine.start(Engine.java:90)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
Usage:
  gpt <op>|<graph-file> [options] [<source-file-1> <source-file-2> ...]

Description: ...
```

**Comment by ramonamanda** [comment]
This warning should not impact any functionality (even if it is logged as severe). It will be changed in the next update (It is implemented but not yet published)

**Comment by S0sh0rt** [comment]
Just installed SNAP 6.0 and I am now receiving this message.  This message was not displayed running SNAP 5.0.

**Comment by andretheronsa** [comment]
I am also getting the message on SNAP 6.0 on Ubuntu.

SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is XXXXXXXXXX

**Comment by mazingaro** [comment]
Same with Snap 6.0.4 :/
